# Generated by Django 3.2.25 on 2025-11-17 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acquisition", "0005_clean"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ontology", "0004_clean"),
        ("equipment", "0003_clean"),
        ("data", "0003_clean"),
        ("api", "0083_update_filerange_bornes_to_datetime"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnnotationCampaignArchive",
            new_name="Archive",
        ),
        migrations.AlterField(
            model_name="archive",
            name="by_user",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="archives",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
