# Generated by Django 3.2.25 on 2025-11-17 15:01

import django.db.models.expressions
from django.db import migrations, models


def migrate_session(apps, schema_editor):
    rel_model = apps.get_model("api", "AnnotationTaskSession")
    session_model = apps.get_model("api", "Session")

    creation = []
    for session in session_model.objects.all():
        creation.append(
            rel_model(
                session_id=session.id,
                annotation_task_id=session.annotation_task_id,
            )
        )
    rel_model.objects.bulk_create(creation)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0084_migrate_osekit__archive"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnnotationSession",
            new_name="Session",
        ),
        migrations.AlterModelTable(
            name="session",
            table=None,
        ),
        migrations.CreateModel(
            name="AnnotationTaskSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.annotationtask",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.session"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="annotationtask",
            name="sessions",
            field=models.ManyToManyField(
                related_name="annotation_tasks",
                through="api.AnnotationTaskSession",
                to="api.Session",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="annotation_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="api.annotationtask",
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(migrate_session, migrations.RunPython.noop),
        migrations.RunSQL(  # TODO: fix reverse migration
            sql=migrations.RunSQL.noop,
            reverse_sql="UPDATE api_session s "
            "SET annotation_task_id = rel.annotation_task_id "
            "FROM api_annotationtasksession rel "
            "WHERE rel.session_id = s.id",
        ),
        migrations.RemoveField(
            model_name="session",
            name="annotation_task",
        ),
    ]
