# Generated by Django 3.2.25 on 2025-11-17 15:01

from django.db import migrations, models


def migrate_session(apps, schema_editor):
    rel_model = apps.get_model("api", "AnnotationTaskSession")
    session_model = apps.get_model("api", "Session")

    creation = []
    for session in session_model.objects.all():
        creation.append(
            rel_model(
                session_id=session.id,
                annotation_task_id=session.annotation_task_id,
            )
        )
    rel_model.objects.bulk_create(creation)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0085_migrate_osekit__annotation_session"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnnotationResultValidation",
            new_name="AnnotationValidation",
        ),
        migrations.RenameField(
            model_name="AnnotationValidation",
            old_name="result",
            new_name="annotation",
        ),
        migrations.AlterUniqueTogether(
            name="annotationvalidation",
            unique_together={("annotation", "annotator")},
        ),
        migrations.AlterField(
            model_name="annotationvalidation",
            name="is_valid",
            field=models.BooleanField(),
        ),
    ]
