# Generated by Django 3.2.25 on 2025-11-17 15:01

import django.db.models.expressions
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


def _get_fft_params(config) -> dict:
    return {
        "nfft": config.nfft,
        "window_size": config.window_size,
        "overlap": round(config.overlap) / 100,
        "sampling_frequency": config.dataset.audio_metadatum.dataset_sr,
        "legacy": True,
    }


def migrate_colormap(apps, schema_editor):
    colormap_model = apps.get_model("api", "Colormap")
    configuration_model = apps.get_model("api", "SpectrogramConfiguration")

    colormap_model.objects.bulk_create(
        [
            colormap_model(name=c)
            for c in list(
                set(configuration_model.objects.values_list("colormap", flat=True))
            )
            if c is not None
        ]
    )


def migrate_fft(apps, schema_editor):
    fft_model = apps.get_model("api", "FFT")
    configuration_model = apps.get_model("api", "SpectrogramConfiguration")

    creation = []
    for config in configuration_model.objects.all():
        creation.append(fft_model(**_get_fft_params(config)))
    fft_model.objects.bulk_create(creation, ignore_conflicts=True)


def migrate_analysis_and_legacy_configuration(apps, schema_editor):
    legacy_configuration_model = apps.get_model("api", "LegacySpectrogramConfiguration")
    analysis_model = apps.get_model("api", "SpectrogramAnalysis")
    configuration_model = apps.get_model("api", "SpectrogramConfiguration")
    colormap_model = apps.get_model("api", "Colormap")
    fft_model = apps.get_model("api", "FFT")

    analysis_creation = []
    legacy_conf_creation = []
    for config in configuration_model.objects.all():
        analysis_creation.append(
            analysis_model(
                id=config.id,
                created_at=config.dataset.created_at,
                name=config.name,
                path=f"processed/spectrogram/{config.dataset.dataset_conf}/{config.name}",
                owner_id=config.dataset.owner_id,
                legacy=True,
                dataset_id=config.dataset_id,
                data_duration=config.spectro_duration,
                fft=fft_model.objects.get(**_get_fft_params(config)),
                colormap=colormap_model.objects.get(name=config.colormap),
                dynamic_min=config.dynamic_min,
                dynamic_max=config.dynamic_max,
                start_date=config.dataset.start_date,
                end_date=config.dataset.end_date,
            )
        )
        file_subtypes = [
            t.name for t in config.dataset.audio_metadatum.files_subtypes.all()
        ]
        legacy_conf_creation.append(
            legacy_configuration_model(
                id=config.id,
                spectrogram_analysis_id=config.id,
                folder=config.name,
                audio_files_subtypes=file_subtypes,
                channel_count=config.dataset.audio_metadatum.channel_count,
                file_overlap=config.audio_file_dataset_overlap,
                zoom_level=config.zoom_level,
                hp_filter_min_frequency=config.hp_filter_min_freq,
                data_normalization=config.data_normalization,
                spectrogram_normalization=config.spectro_normalization,
                frequency_resolution=config.frequency_resolution,
                zscore_duration=config.zscore_duration,
                window_type=config.window_type.name if config.window_type else None,
                peak_voltage=config.peak_voltage,
                sensitivity_dB=config.sensitivity_dB,
                temporal_resolution=config.temporal_resolution,
                linear_frequency_scale_id=config.linear_frequency_scale_id,
                multi_linear_frequency_scale_id=config.multi_linear_frequency_scale_id,
                gain_dB=config.gain_dB,
            )
        )

    analysis_model.objects.bulk_create(analysis_creation)
    legacy_configuration_model.objects.bulk_create(legacy_conf_creation)


def set_datasets_as_legacy(apps, schema_editor):
    dataset_model = apps.get_model("api", "Dataset")
    dataset_model.objects.all().update(legacy=True)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0086_migrate_osekit__annotation_validation"),
    ]

    operations = [
        # Colormap
        migrations.CreateModel(
            name="Colormap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(migrate_colormap, migrations.RunPython.noop),
        # FFT
        migrations.CreateModel(
            name="FFT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nfft", models.IntegerField()),
                ("window_size", models.IntegerField()),
                ("overlap", models.DecimalField(decimal_places=2, max_digits=3)),
                ("sampling_frequency", models.PositiveIntegerField()),
                ("scaling", models.CharField(blank=True, max_length=50, null=True)),
                ("legacy", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="fft",
            unique_together={("nfft", "window_size", "overlap", "sampling_frequency")},
        ),
        migrations.RunPython(migrate_fft, migrations.RunPython.noop),
        # Analysis
        migrations.CreateModel(
            name="SpectrogramAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("path", models.CharField(max_length=255)),
                (
                    "data_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Duration of the segmented data (in s)",
                        null=True,
                    ),
                ),
                ("dynamic_min", models.FloatField()),
                ("dynamic_max", models.FloatField()),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("legacy", models.BooleanField(default=False)),
                (
                    "colormap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spectrogram_analysis",
                        to="api.colormap",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spectrogram_analysis",
                        to="api.dataset",
                    ),
                ),
                (
                    "fft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spectrogram_analysis",
                        to="api.fft",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spectrogram_analysis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Spectrogram analysis",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="spectrogramanalysis",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("legacy", True),
                    models.Q(("data_duration__isnull", False), ("legacy", False)),
                    _connector="OR",
                ),
                name="spectrogram_analysis_legacy",
            ),
        ),
        # Legacy configuration
        migrations.CreateModel(
            name="LegacySpectrogramConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder", models.CharField(max_length=255)),
                (
                    "audio_files_subtypes",
                    ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("channel_count", models.IntegerField(blank=True, null=True)),
                ("file_overlap", models.IntegerField(blank=True, null=True)),
                ("zoom_level", models.IntegerField()),
                ("hp_filter_min_frequency", models.IntegerField()),
                ("data_normalization", models.CharField(max_length=255)),
                ("frequency_resolution", models.FloatField()),
                ("spectrogram_normalization", models.CharField(max_length=255)),
                (
                    "zscore_duration",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "window_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("peak_voltage", models.FloatField(blank=True, null=True)),
                ("sensitivity_dB", models.FloatField(blank=True, null=True)),
                ("temporal_resolution", models.FloatField(blank=True, null=True)),
                ("gain_dB", models.FloatField(blank=True, null=True)),
                (
                    "linear_frequency_scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.linearscale",
                    ),
                ),
                (
                    "multi_linear_frequency_scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.multilinearscale",
                    ),
                ),
                (
                    "spectrogram_analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_configuration",
                        to="api.spectrogramanalysis",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="legacyspectrogramconfiguration",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("linear_frequency_scale__isnull", True),
                        ("multi_linear_frequency_scale__isnull", False),
                    ),
                    models.Q(
                        ("linear_frequency_scale__isnull", False),
                        ("multi_linear_frequency_scale__isnull", True),
                    ),
                    models.Q(
                        ("linear_frequency_scale__isnull", True),
                        ("multi_linear_frequency_scale__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="legacy_spectrogram_configuration_max_one_scale",
            ),
        ),
        migrations.RunPython(
            migrate_analysis_and_legacy_configuration, migrations.RunPython.noop
        ),
        # Dataset
        migrations.AlterModelOptions(
            name="dataset",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="desc",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="dataset_path",
            new_name="path",
        ),
        migrations.AddField(
            model_name="dataset",
            name="legacy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataset",
            name="related_channel_configurations",
            field=models.ManyToManyField(
                related_name="datasets", to="acquisition.ChannelConfiguration"
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="dataset",
            unique_together={("name", "path")},
        ),
        migrations.AlterModelTable(
            name="dataset",
            table=None,
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="audio_metadatum",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="dataset_conf",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="dataset_type",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="files_type",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="geo_metadatum",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="related_channel_configuration",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="status",
        ),
        migrations.RunSQL(
            "SELECT setval('api_legacyspectrogramconfiguration_id_seq', (SELECT max(id) from api_legacyspectrogramconfiguration)); "
            "SELECT setval('api_spectrogramanalysis_id_seq', (SELECT max(id) from api_spectrogramanalysis)) ",
            migrations.RunSQL.noop,
        ),
        # Clean
        migrations.RunPython(set_datasets_as_legacy, migrations.RunPython.noop),
    ]
