# Generated by Django 3.2.25 on 2025-11-17 15:01

import django.db.models.expressions
from django.db import migrations, models


def create_png_file_format(apps, schema_editor):
    format_model = apps.get_model("data", "FileFormat")
    format_model.objects.get_or_create(name="png")


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_clean"),
        ("api", "0087_migrate_osekit__analysis"),
    ]

    operations = [
        # Spectrogram
        migrations.RenameModel(
            old_name="DatasetFile",
            new_name="Spectrogram",
        ),
        migrations.AlterModelTable(
            name="Spectrogram",
            table=None,
        ),
        migrations.RemoveField(
            model_name="Spectrogram",
            name="filepath",
        ),
        migrations.RemoveField(
            model_name="Spectrogram",
            name="size",
        ),
        migrations.AddField(
            model_name="spectrogram",
            name="analysis",
            field=models.ManyToManyField(
                related_name="spectrograms", to="api.SpectrogramAnalysis"
            ),
        ),
        migrations.AddField(
            model_name="spectrogram",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="data.fileformat",
                null=True,
                blank=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="spectrogram",
            constraint=models.CheckConstraint(
                check=models.Q(("start__lt", django.db.models.expressions.F("end"))),
                name="start is lower than end",
            ),
        ),
        migrations.RunPython(create_png_file_format, migrations.RunPython.noop),
        migrations.RunSQL(
            """
                UPDATE api_spectrogram s
                SET filename = substring(s.filename, 0, position('.' in s.filename)),
                    format_id = (SELECT id FROM metadatax_data_fileformat WHERE name='png')
                """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "INSERT INTO api_spectrogram_analysis (spectrogramanalysis_id, spectrogram_id)"
            "SELECT c.id, s.id "
            "FROM api_spectrogram s "
            "LEFT JOIN api_dataset d on d.id = s.dataset_id "
            "LEFT JOIN api_spectrogramconfiguration c on c.dataset_id = d.id;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="spectrogram",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="data.fileformat"
            ),
        ),
        migrations.RemoveField(
            model_name="Spectrogram",
            name="dataset",
        ),
    ]
