# Generated by Django 3.2.25 on 2025-11-17 15:01

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0088_migrate_osekit__spectrogram"),
    ]

    operations = [
        # AnnotationCampaignAnalysis
        migrations.CreateModel(
            name="AnnotationCampaignAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.spectrogramanalysis",
                    ),
                ),
                (
                    "annotation_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.annotationcampaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("annotation_campaign", "analysis")},
            },
        ),
        # AnnotationCampaign
        migrations.RenameField(
            model_name="annotationcampaign",
            old_name="confidence_indicator_set",
            new_name="confidence_set",
        ),
        migrations.RenameField(
            model_name="annotationcampaign",
            old_name="desc",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="annotationcampaign",
            name="annotation_scope",
        ),
        migrations.AlterField(
            model_name="annotationcampaign",
            name="instructions_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationcampaign",
            name="label_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.labelset",
            ),
        ),
        migrations.AlterModelTable(
            name="annotationcampaign",
            table=None,
        ),
        migrations.AlterField(
            model_name="annotationcampaign",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="annotationcampaign",
            name="archive",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotation_campaign",
                to="api.archive",
            ),
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="analysis",
            field=models.ManyToManyField(
                related_name="annotation_campaigns",
                through="api.AnnotationCampaignAnalysis",
                to="api.SpectrogramAnalysis",
            ),
        ),
        migrations.RunSQL(
            "INSERT INTO api_annotationcampaignanalysis(analysis_id, annotation_campaign_id) "
            "SELECT spectrogramconfiguration_id, annotationcampaign_id "
            "FROM api_annotationcampaign_spectro_configs",
            migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name="annotationcampaign",
            name="spectro_configs",
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotation_campaigns",
                to="api.dataset",
            ),
            preserve_default=False,
        ),
    ]
