# Generated by Django 3.2.25 on 2025-11-17 15:01

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_migrate_osekit__campaign"),
    ]

    operations = [
        # AnnotationCampaign
        migrations.RunSQL(
            "UPDATE api_annotationcampaign c "
            "SET dataset_id = d.dataset_id "
            "FROM api_annotationcampaign_datasets d WHERE c.id = d.annotationcampaign_id",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="annotationcampaign",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotation_campaigns",
                to="api.dataset",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="annotationcampaign",
            name="datasets",
        ),
        # AnnotationPhase
        migrations.RenameModel(
            old_name="AnnotationCampaignPhase",
            new_name="AnnotationPhase",
        ),
    ]
