# Generated by Django 3.2.25 on 2025-11-17 15:01

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0090_migrate_osekit__phase"),
    ]

    operations = [
        # Confidence
        migrations.RenameModel(
            old_name="ConfidenceIndicatorSet",
            new_name="ConfidenceSet",
        ),
        migrations.RemoveConstraint(
            model_name="confidenceindicatorsetindicator",
            name="one_default_indicator_by_set",
        ),
        migrations.RemoveConstraint(
            model_name="confidenceindicatorsetindicator",
            name="no_duplicate_indicator_in_set",
        ),
        migrations.RenameField(
            model_name="confidenceindicatorsetindicator",
            old_name="confidence_indicator",
            new_name="confidence",
        ),
        migrations.RenameField(
            model_name="confidenceindicatorsetindicator",
            old_name="confidence_indicator_set",
            new_name="confidence_set",
        ),
        migrations.AddConstraint(
            model_name="confidenceindicatorsetindicator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default", "confidence_set"),
                name="one_default_confidence_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="confidenceindicatorsetindicator",
            constraint=models.UniqueConstraint(
                fields=("confidence", "confidence_set"),
                name="no_duplicate_confidence_in_set",
            ),
        ),
        migrations.RenameModel(
            old_name="ConfidenceIndicator",
            new_name="Confidence",
        ),
        # Label
        migrations.RenameField(
            model_name="labelset",
            old_name="desc",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="label",
            name="metadatax_label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ontology.label",
            ),
        ),
        # AcousticFeatures
        migrations.RenameModel(
            old_name="AnnotationResultAcousticFeatures",
            new_name="AcousticFeatures",
        ),
        migrations.AlterModelOptions(
            name="acousticfeatures",
            options={"verbose_name_plural": "Acoustic features"},
        ),
        # Annotation
        migrations.RenameModel(
            old_name="AnnotationResult",
            new_name="Annotation",
        ),
        migrations.AlterModelTable(
            name="Annotation",
            table=None,
        ),
        migrations.RenameField(
            model_name="Annotation",
            old_name="confidence_indicator",
            new_name="confidence",
        ),
        migrations.RenameField(
            model_name="Annotation",
            old_name="annotation_campaign_phase",
            new_name="annotation_phase",
        ),
        migrations.AlterField(
            model_name="annotation",
            name="annotation_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.annotationphase",
            ),
        ),
        migrations.RenameField(
            model_name="Annotation",
            old_name="dataset_file",
            new_name="spectrogram",
        ),
        migrations.AlterField(
            model_name="annotation",
            name="spectrogram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.spectrogram",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="annotation",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.spectrogramanalysis",
                null=True,
            ),
        ),
        migrations.RunSQL(
            "UPDATE api_annotation annotation "
            "SET analysis_id = a.spectrogramanalysis_id "
            "FROM api_spectrogram_analysis a "
            "WHERE annotation.spectrogram_id = a.spectrogram_id",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="annotation",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.spectrogramanalysis",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="detector_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.detectorconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="annotator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="acoustic_features",
            field=models.OneToOneField(
                blank=True,
                help_text="Acoustic features add a better description to the signal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotation",
                to="api.acousticfeatures",
            ),
        ),
    ]
