# Generated by Django 3.2.25 on 2025-11-17 15:01

from django.db import migrations, models


def clean_start_status(apps, schema_editor):
    task_model = apps.get_model("api", "AnnotationTask")
    task_model.objects.filter(status="S").update(status="C")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0091_migrate_osekit__annotation"),
    ]

    operations = [
        # AnnotationTask
        migrations.AlterModelOptions(
            name="annotationtask",
            options={"ordering": ["spectrogram__start", "id"]},
        ),
        migrations.RenameField(
            model_name="annotationtask",
            old_name="annotation_campaign_phase",
            new_name="annotation_phase",
        ),
        migrations.AlterField(
            model_name="annotationtask",
            name="annotation_phase",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="annotation_tasks",
                to="api.annotationphase",
            ),
        ),
        migrations.RenameField(
            model_name="annotationtask",
            old_name="dataset_file",
            new_name="spectrogram",
        ),
        migrations.AlterField(
            model_name="annotationtask",
            name="spectrogram",
            field=models.ForeignKey(
                on_delete=models.deletion.PROTECT,
                related_name="annotation_tasks",
                to="api.spectrogram",
            ),
        ),
        migrations.AlterField(
            model_name="annotationtask",
            name="status",
            field=models.TextField(
                choices=[("C", "Created"), ("F", "Finished")], default="C"
            ),
        ),
        # AnnotationFileRange
        migrations.RenameField(
            model_name="annotationfilerange",
            old_name="annotation_campaign_phase",
            new_name="annotation_phase",
        ),
        migrations.AlterField(
            model_name="annotationfilerange",
            name="annotation_phase",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="annotation_file_ranges",
                to="api.annotationphase",
            ),
        ),
        # Clean
        migrations.RunPython(clean_start_status, migrations.RunPython.noop),
    ]
