# Generated by Django 3.2.25 on 2025-11-17 15:01

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models
from django.utils.datetime_safe import datetime


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0092_migrate_osekit__annotation_task"),
    ]

    operations = [
        # AnnotationComment
        migrations.RenameField(
            model_name="annotationcomment",
            old_name="annotation_campaign_phase",
            new_name="annotation_phase",
        ),
        migrations.AlterField(
            model_name="annotationcomment",
            name="annotation_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_comments",
                to="api.annotationphase",
            ),
        ),
        migrations.RenameField(
            model_name="annotationcomment",
            old_name="annotation_result",
            new_name="annotation",
        ),
        migrations.AlterField(
            model_name="annotationcomment",
            name="annotation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_comments",
                to="api.annotation",
            ),
        ),
        migrations.RenameField(
            model_name="annotationcomment",
            old_name="dataset_file",
            new_name="spectrogram",
        ),
        migrations.AlterField(
            model_name="annotationcomment",
            name="spectrogram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_comments",
                to="api.spectrogram",
            ),
        ),
        migrations.AddField(
            model_name="annotationcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="annotationcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="annotationcomment",
            table=None,
        ),
    ]
