# Generated by Django 3.2.25 on 2025-11-17 15:01

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models
from django.utils.datetime_safe import datetime


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_clean"),
        ("api", "0093_migrate_osekit__annotation_comment"),
    ]

    operations = [
        # Detector
        migrations.AddField(
            model_name="detector",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equipment.acousticdetectorspecification",
            ),
        ),
        migrations.AlterField(
            model_name="detectorconfiguration",
            name="configuration",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="detectorconfiguration",
            unique_together={("configuration", "detector")},
        ),
    ]
