# Generated by Django 3.2.25 on 2025-11-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0094_migrate_osekit__detector"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DatasetType",
        ),
        migrations.DeleteModel(
            name="GeoMetadatum",
        ),
        migrations.DeleteModel(
            name="AudioMetadatum",
        ),
        migrations.DeleteModel(
            name="FileSubtype",
        ),
        migrations.DeleteModel(
            name="SpectrogramConfiguration",
        ),
        migrations.DeleteModel(
            name="WindowType",
        ),
    ]
