# Generated by Django 3.2.25 on 2025-11-24 09:56

from django.db import migrations, models
from django.db.models import Min, Max


def add_start_end(apps, schema_editor):
    analysis_model = apps.get_model("api", "SpectrogramAnalysis")

    for analysis in analysis_model.objects.all():
        info = analysis.spectrograms.aggregate(start=Min("start"), end=Max("end"))
        analysis.start = info["start"]
        analysis.end = info["end"]
        analysis.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0095_migrate_osekit__clean"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectrogramanalysis",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spectrogramanalysis",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(add_start_end, migrations.RunPython.noop),
    ]
