# Generated by Django 3.2.25 on 2026-01-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0096_migrate_osekit__add_start_end_to_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spectrogramanalysis",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="spectrogramanalysis",
            name="start_date",
        ),
        migrations.AlterUniqueTogether(
            name="fft",
            unique_together={
                (
                    "nfft",
                    "window_size",
                    "overlap",
                    "sampling_frequency",
                    "scaling",
                    "legacy",
                )
            },
        ),
    ]
