"""API GQL Nodes"""
from .acoustic_features import AcousticFeaturesNode
from .annotation import AnnotationNode
from .annotation_campaign import AnnotationCampaignNode
from .annotation_comment import AnnotationCommentNode
from .annotation_file_range import AnnotationFileRangeNode
from .annotation_phase import AnnotationPhaseNode
from .annotation_spectrogram import AnnotationSpectrogramNode
from .annotation_task import AnnotationTaskNode
from .annotation_validation import AnnotationValidationNode
from .archive import ArchiveNode
from .colormap import ColormapNode
from .confidence import ConfidenceNode
from .confidence_set import ConfidenceSetNode
from .dataset import DatasetNode
from .detector import DetectorNode
from .detector_configuration import DetectorConfigurationNode
from .fft import FFTNode
from .import_analysis import ImportAnalysisNode
from .import_dataset import ImportDatasetNode
from .label import AnnotationLabelNode
from .label_set import LabelSetNode
from .legacy_spectrogram_configuration import LegacySpectrogramConfigurationNode
from .linear_scale import LinearScaleNode
from .multi_linear_scale import MultiLinearScaleNode
from .spectrogram import SpectrogramNode
from .spectrogram_analysis import SpectrogramAnalysisNode
